import { Download, FileText, Search, Zap } from "lucide-react";

export const features = [
  {
    icon: Zap,
    title: 'Real-time AI Writing',
    description:
      'Generate high-quality content instantly with our advanced AI engine',
  },
  {
    icon: Search,
    title: 'SEO-Optimized Content',
    description: 'Built-in SEO optimization to help your content rank higher',
  },
  {
    icon: FileText,
    title: 'Multiple Writing Styles',
    description: 'From blogs to ads, choose from 50+ writing templates',
  },
  {
    icon: Download,
    title: 'Export to Word or PDF',
    description: 'Seamlessly export your content in multiple formats',
  },
];

export const testimonials = [
  {
    name: 'Sarah Johnson',
    role: 'Content Marketing Manager',
    company: 'TechCorp',
    image:
      'https://images.unsplash.com/photo-1494790108755-2616b612b605?w=100&h=100&fit=crop&crop=face',
    quote:
      "AIWriterPro has revolutionized our content creation process. We're producing 3x more content with better quality.",
  },
  {
    name: 'Michael Chen',
    role: 'Freelance Writer',
    company: 'Independent',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    quote:
      "The AI suggestions are incredibly accurate. It's like having a writing partner who never runs out of ideas.",
  },
  {
    name: 'Emily Rodriguez',
    role: 'Marketing Director',
    company: 'StartupXYZ',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    quote:
      'Our conversion rates increased by 40% after using AIWriterPro for our marketing copy.',
  },
];

export const pricingTiers = [
  {
    name: 'Free',
    price: '$0',
    period: '/month',
    description: 'Perfect for trying out AIWriterPro',
    features: [
      '5,000 words per month',
      '3 writing templates',
      'Basic support',
      'Export to PDF',
    ],
    cta: 'Start Free',
    popular: false,
  },
  {
    name: 'Pro',
    price: '$29',
    period: '/month',
    description: 'Best for professionals and small teams',
    features: [
      '100,000 words per month',
      '50+ writing templates',
      'Priority support',
      'Export to Word & PDF',
      'SEO optimization',
      'Plagiarism checker',
    ],
    cta: 'Start Free Trial',
    popular: true,
  },
  {
    name: 'Enterprise',
    price: '$99',
    period: '/month',
    description: 'For large teams and agencies',
    features: [
      'Unlimited words',
      'All writing templates',
      '24/7 dedicated support',
      'All export formats',
      'Advanced SEO tools',
      'Team collaboration',
      'Custom integrations',
      'White-label option',
    ],
    cta: 'Contact Sales',
    popular: false,
  },
];

export const faqs = [
  {
    question: 'How does AIWriterPro work?',
    answer:
      'AIWriterPro uses advanced AI models to understand your content requirements and generate high-quality, original content. Simply provide a topic or brief, select a template, and our AI will create engaging content tailored to your needs.',
  },
  {
    question: 'Is the content generated by AI original?',
    answer:
      'Yes, all content generated by AIWriterPro is original and unique. Our AI creates content from scratch based on your inputs, ensuring no plagiarism issues.',
  },
  {
    question: 'Can I customize the writing style?',
    answer:
      'Absolutely! AIWriterPro offers multiple writing styles and tones. You can adjust the formality, creativity level, and target audience to match your brand voice.',
  },
  {
    question: 'What happens if I exceed my word limit?',
    answer:
      "If you exceed your monthly word limit, you can either upgrade your plan or wait until the next billing cycle. We'll notify you when you're approaching your limit.",
  },
  {
    question: 'Do you offer refunds?',
    answer:
      "Yes, we offer a 30-day money-back guarantee for all paid plans. If you're not satisfied with AIWriterPro, contact our support team for a full refund.",
  },
];
